name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: scvready/esphomekit:latest
      volumes:
        - ${{ github.workspace }}:/home/project
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Build
        working-directory: ${{github.workspace}}
        run: ./docker_entry.sh /home /home/project
