name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # CHANGE
    runs-on: ubuntu-latest
    container: scvready/esphomekit:latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ${{github.workspace}}
        run: ./build.sh