name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: scvready/esphomekit:latest
      volumes:
        - .:/home/project
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        working-directory: ${{github.workspace}}
        run: ./docker_entry.sh /home /home/project
